services:
  - type: web
    name: aura-essence-api
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    releaseCommand: "python manage.py migrate --noinput && python manage.py collectstatic --no-input"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        value: "postgresql://aura_essence_user:zOxrKcUTQ393OMWyjXa1VS35txSgrg3m@dpg-d6fovu15pdvs73flpueg-a.oregon-postgres.render.com/aura_essence_wzwi?sslmode=require"
      - key: PYTHON_VERSION
        value: 3.11.8

databases:
  - name: aura-essence-db
    databaseName: aura_essence
    user: aura_essence_user
